### ISSUE TITLE
PA Review User Authentication

### ISSUE THREAD

**Issue by parkg748** [parkg748/stART#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by rkoron007** [comment]
Just check the boxes and assign this to me to review when you are ready :)

**Comment by rkoron007** [comment]
## Sign Up Form:
![screen shot 2018-10-16 at 5 38 34 pm](https://user-images.githubusercontent.com/32436232/47055052-6077c280-d16a-11e8-9278-e1d735ce6487.png)
- something is going on with your sign up form email validation
  - it won't let me submit even with a valid email

## Demo Button
- Your demo button doesn't seem to work on heroku

### For Styling:
![screen shot 2018-10-16 at 5 34 38 pm](https://user-images.githubusercontent.com/32436232/47054984-f2cb9680-d169-11e8-8d3d-cba6fba2cf37.png)
![screen shot 2018-10-16 at 5 34 43 pm](https://user-images.githubusercontent.com/32436232/47054985-f2cb9680-d169-11e8-8832-609bcbf4ad8c.png)
- Make sure your  bar listing all the project stats at extends across the page.

**Comment by rkoron007** [comment]
Let me know whenever you'd like me to re-review this :)

**Comment by parkg748** [comment]
I'm ready for a review! Let me know when you are.

**Comment by rkoron007** [comment]
Looks like your site is down on Heroku right now? Just slack me when it's back up :)

**Comment by rkoron007** [comment]
Looks like errors aren't showing for your login page: 
![screen shot 2018-10-18 at 1 37 00 pm](https://user-images.githubusercontent.com/32436232/47182876-7a84e280-d2db-11e8-9f29-827d6e7b57fb.png)

---
- The Navbar looks like it's on both the login and signup forms too
![screen shot 2018-10-18 at 1 44 36 pm](https://user-images.githubusercontent.com/32436232/47183083-fb43de80-d2db-11e8-8092-3f5aec4b2f65.png)

- Your styling is 🔥  though!

**Comment by rkoron007** [comment]
Let me know if you'd like me to re-review this!
